# Generated by Django 4.2 on 2023-05-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='original_filename',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
